// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskFlow.Infrastructure.Persistence;

#nullable disable

namespace TaskFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318031845_AddColumnParentTaskId")]
    partial class AddColumnParentTaskId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.Domain.Entities.List", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriado");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlterado");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lista", (string)null);
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCompletada");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriado");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Descricao");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Completada");

                    b.Property<Guid?>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdLista");

                    b.Property<bool>("Notify")
                        .HasColumnType("boolean")
                        .HasColumnName("NotificarAgendamento");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTaskPai");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Prioridade");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlterado");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriado");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("Nome");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Senha");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlterado");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.List", b =>
                {
                    b.HasOne("TaskFlow.Domain.Entities.User", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Task", b =>
                {
                    b.HasOne("TaskFlow.Domain.Entities.List", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskFlow.Domain.Entities.Task", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskFlow.Domain.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaskFlow.Domain.ValueObjects.Scheduling", "Scheduling", b1 =>
                        {
                            b1.Property<Guid>("TaskId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("DataAgendamento");

                            b1.Property<string>("Recurrence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Recorrencia");

                            b1.Property<TimeOnly?>("Time")
                                .HasColumnType("time without time zone")
                                .HasColumnName("HoraAgendamento");

                            b1.HasKey("TaskId");

                            b1.ToTable("Tarefa");

                            b1.WithOwner()
                                .HasForeignKey("TaskId");
                        });

                    b.Navigation("List");

                    b.Navigation("ParentTask");

                    b.Navigation("Scheduling");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.User", b =>
                {
                    b.OwnsOne("TaskFlow.Domain.ValueObjects.AvatarUrl", "AvatarUrl", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Url")
                                .HasColumnType("text")
                                .HasColumnName("AvatarUrl");

                            b1.HasKey("UserId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("TaskFlow.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Address")
                                .IsUnique();

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AvatarUrl")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.List", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Task", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
